force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs available for being included into Mixes. Has Name, Artist, Length and Genre</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of song</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Hip hop</fullName>
            </value>
            <value>
                <fullName>K-pop</fullName>
            </value>
            <value>
                <fullName>Latin</fullName>
            </value>
            <value>
                <fullName>Polka</fullName>
            </value>
            <value>
                <fullName>Punk</fullName>
            </value>
            <value>
                <fullName>R&amp;B</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandler/SongTriggerHandler.cls
public class SongTriggerHandler implements TriggerTemplate.Handler {
    
    private List<Song__c> newValues;
	private Map<Id, Song__c> oldValues;

    public void setValues(List<sObject> newValues, Map<Id, sObject> oldValues)
	{
		this.newValues = (List<Song__c>)newValues;
		this.oldValues = (Map<Id, Song__c>)oldValues;
	}

    public void handle(TriggerTemplate.TriggerAction action) {
        Set<Id> songsWithMixesToBeUpdatedIdSet = new Set<Id>();

        if (action == TriggerTemplate.TriggerAction.afterupdate) {
            for (Song__c newSong: newValues) {
                if (newSong.Genre__c != oldValues.get(newSong.Id).Genre__c) {
                    songsWithMixesToBeUpdatedIdSet.add(newSong.Id);
                }
            }
        }

        Set<Id> mixesToUpdateIdSet = SongTriggerHelper.getMixesToUpdateGenres(songsWithMixesToBeUpdatedIdSet);

        MixService.updateMixesInfo(mixesToUpdateIdSet);
    }
}