force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs available for being included into Mixes. Has Name, Artist, Length and Genre</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Track_Amount__c.field-meta.xml
<CustomField>
    <fullName>Track_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How much related tracks alreadt exists: cannot be more than Track Licenses field</description>
    <label>Track Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{00000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Service/SongService.cls
public class SongService {
    public static void updateTrackCount(Set<Id> songsToUpdateIdSet) {
        if (songsToUpdateIdSet.isEmpty()) {
            return;
        }

        List<Song__c> songsToUpdateList = [SELECT Id, 
                                                    Track_Amount__c, 
                                                    (SELECT Id FROM Tracks__r) 
                                            FROM Song__c
                                            WHERE Id IN :songsToUpdateIdSet];

        for (Song__c song: songsToUpdateList) {
            song.Track_Amount__c = song.Tracks__r.size();
        }

        update songsToUpdateList;
    }
}