force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs available for being included into Mixes. Has Name, Artist, Length and Genre</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{00000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TrackTriggerHandler.cls
public class TrackTriggerHandler implements TriggerTemplate.Handler {
    private List<Track__c> newValues;
	private Map<Id, Track__c> oldValues;

    public void setValues(List<sObject> newValues, Map<Id, sObject> oldValues)
	{
		this.newValues = (List<Track__c>)newValues;
		this.oldValues = (Map<Id, Track__c>)oldValues;
	}
    
    public void handle(TriggerTemplate.TriggerAction action) {
        if (action == TriggerTemplate.TriggerAction.afterinsert) {
            Set<Id> songToUpdateIds = new Set<Id>();
            Set<Id> mixesToUpdateIds = new Set<Id>();
            
            for (Track__c track: newValues) {
                songToUpdateIds.add(track.Song__c);
                mixesToUpdateIds.add(track.Mix__c);
            }

            //Service classes call
        }

        if (action == TriggerTemplate.TriggerAction.afterupdate) {
            Set<Id> songToUpdateIds = new Set<Id>();
            Set<Id> mixesToUpdateIds = new Set<Id>();

            for (Track__c newTrack: newValues) {
                if(newTrack.Song__c != oldValues.get(newTrack.Id).Song__c) {
                    songToUpdateIds.add(newTrack.Song__c);
                    songToUpdateIds.add(oldValues.get(newTrack.Id).Song__c);

                    mixesToUpdateIds.add(newTrack.Mix__c);
                    mixesToUpdateIds.add(oldValues.get(newTrack.Id).Mix__c);

                }
            }

            //Service class call
        }

        if (action == TriggerTemplate.TriggerAction.afterdelete) {
            Set<Id> songToUpdateIds = new Set<Id>();
            Set<Id> mixesToUpdateIds = new Set<Id>();

            for (Track__c track: oldValues.values()) {
                songToUpdateIds.add(track.Song__c);
                mixesToUpdateIds.add(track.Mix__c);
            }

            //Service call
        }
    }
}