force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of Mix in minutes and seconds</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Primary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Primary_Genre__c</fullName>
    <description>Moxt frequent genre of songs</description>
    <label>Primary Genre</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Secondary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Genre__c</fullName>
    <description>second most frequent genre of songs</description>
    <label>Secondary Genre</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Song_Amount__c.field-meta.xml
<CustomField>
    <fullName>Song_Amount__c</fullName>
    <description>Amount of songs related to mix</description>
    <label>Song Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs available for being included into Mixes. Has Name, Artist, Length and Genre</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <description>Artist who sings this song</description>
    <label>Artist</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of song in minutes and seconds</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of song</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Hip hop</fullName>
            </value>
            <value>
                <fullName>K-pop</fullName>
            </value>
            <value>
                <fullName>Latin</fullName>
            </value>
            <value>
                <fullName>Polka</fullName>
            </value>
            <value>
                <fullName>Punk</fullName>
            </value>
            <value>
                <fullName>R&amp;B</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Amount__c.field-meta.xml
<CustomField>
    <fullName>Track_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How much related tracks alreadt exists: cannot be more than Track Licenses field</description>
    <label>Track Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Track_Licenses__c</fullName>
    <description>Amount of licenses available for this song: how much times song can be used in Mix</description>
    <label>Track Licenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{00000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test/TrackTriggerTests.cls
@isTest
public class TrackTriggerTests {
    @testSetup
    public static void createData() {
        Song__c hipHop1 = new Song__c(Artist__c = 'name1', Name = 'hip_hop_1', Duration__c = 2.42, Genre__c = 'Hip hop', Track_Amount__c = 1, Track_Licenses__c = 3);
        Song__c hipHop2 = new Song__c(Artist__c = 'name1', Name = 'hip_hop_2', Duration__c = 3.37, Genre__c = 'Hip hop', Track_Amount__c = 0, Track_Licenses__c = 3);
        Song__c hipHop3 = new Song__c(Artist__c = 'name1', Name = 'hip_hop_3', Duration__c = 3.45, Genre__c = 'Hip hop', Track_Amount__c = 0, Track_Licenses__c = 3);

        Song__c rock1 = new Song__c(Artist__c = 'name1', Name = 'rock_1', Duration__c = 4.17, Genre__c = 'Rock', Track_Amount__c = 0, Track_Licenses__c = 3);
        Song__c rock2 = new Song__c(Artist__c = 'name1', Name = 'rock_2', Duration__c = 4.21, Genre__c = 'Rock', Track_Amount__c = 0, Track_Licenses__c = 3);
        
        Mix__c mixWithTracks = new Mix__c(Name = 'Mix One');
        Mix__c mixWithoutTracks = new Mix__c(Name = 'Mix Two');

        insert new List<SObject> {
            hipHop1,
            hipHop2,
            hipHop3,
            rock1,
            rock2,
            mixWithTracks, 
            mixWithoutTracks
        };
        
        insert new List<Track__c> {
            new Track__c(Song__c = hipHop1.Id, Mix__c = mixWithTracks.Id)
        };
    }

    @isTest
    public static void trackAmountIsChangedAfterInsertTest() {
        Song__c hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];
        Mix__c mixWithoutSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix Two' LIMIT 1];

        Decimal trackAmountExpected = hipHop1.Track_Amount__c + 1;

        Test.startTest();

            Track__c newTrack = new Track__c(Song__c = hipHop1.Id, Mix__c = mixWithoutSongs.Id);
            insert newTrack;

        Test.stopTest();

        hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];
        mixWithoutSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix One' LIMIT 1];

        System.assertEquals(trackAmountExpected, hipHop1.Track_Amount__c, 'Track amount is not like expected');
    }

    @isTest
    public static void trackAmountIsChangedAfterDeleteTest() {
        Song__c hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];

        Decimal hipHop1ExpectedCount = hipHop1.Track_Amount__c - 1;

        Test.startTest();

            Track__c track = [SELECT Id FROM Track__c WHERE Song__c = :hipHop1.Id LIMIT 1];
            delete track;

        Test.stopTest();

        hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];        

        System.assertEquals(hipHop1ExpectedCount, hipHop1.Track_Amount__c, 'Track count is not like expected (hipHop1)');
    }

    @isTest
    public static void mixGenresAreUpdatedAfterInsertTest() {
        Song__c hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];
        Song__c hipHop2 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_3' LIMIT 1];
        Song__c hipHop3 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_3' LIMIT 1];
        Song__c rock1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'rock_1' LIMIT 1];
        Song__c rock2 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'rock_2' LIMIT 1];

        Mix__c mixWithoutSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix Two' LIMIT 1];

        Test.startTest();

            insert new List<Track__c>{
                new Track__c(Song__c = hipHop1.Id, Mix__c = mixWithoutSongs.Id),
                new Track__c(Song__c = hipHop2.Id, Mix__c = mixWithoutSongs.Id),
                new Track__c(Song__c = hipHop3.Id, Mix__c = mixWithoutSongs.Id),
                new Track__c(Song__c = rock1.Id, Mix__c = mixWithoutSongs.Id),
                new Track__c(Song__c = rock2.Id, Mix__c = mixWithoutSongs.Id)
            };

        Test.stopTest();

        mixWithoutSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix Two' LIMIT 1];

        System.assertEquals('Hip hop', mixWithoutSongs.Primary_Genre__c, 'Primary genre was not updated');

        System.assertEquals('Rock', mixWithoutSongs.Secondary_Genre__c, 'Secondary genre was not updated');
    }

    @isTest
    public static void mixGenresAreUpdatedAfterDeleteTest() {
        Song__c hipHop1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_1' LIMIT 1];
        Song__c hipHop2 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_2' LIMIT 1];
        Song__c hipHop3 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'hip_hop_3' LIMIT 1];
        Song__c rock1 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'rock_1' LIMIT 1];
        Song__c rock2 = [SELECT Id, Track_Amount__c FROM Song__c WHERE Name = 'rock_2' LIMIT 1];

        Mix__c mixWithSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix One' LIMIT 1];


        insert new List<Track__c>{
            new Track__c(Song__c = hipHop2.Id, Mix__c = mixWithSongs.Id),
            new Track__c(Song__c = hipHop3.Id, Mix__c = mixWithSongs.Id),
            new Track__c(Song__c = rock1.Id, Mix__c = mixWithSongs.Id),
            new Track__c(Song__c = rock2.Id, Mix__c = mixWithSongs.Id)
        };

        Test.startTest();

            Set<Id> hipHopToDeleteIdSet = new Set<Id>{hipHop1.Id, hipHop2.Id};

            delete [SELECT Id FROM Track__c WHERE Song__c IN :hipHopToDeleteIdSet AND Mix__c = :mixWithSongs.Id];

        Test.stopTest();

        mixWithSongs = [SELECT Id, Song_Amount__c, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Name = 'Mix One' LIMIT 1];

        System.assertEquals('Rock', mixWithSongs.Primary_Genre__c, 'Primary Genre was not updated');

        System.assertEquals('Hip hop', mixWithSongs.Secondary_Genre__c, 'Secondary Genre was not updated');

    }
}