force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Primary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Primary_Genre__c</fullName>
    <description>Moxt frequent genre of songs</description>
    <label>Primary Genre</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mix__c/fields/Secondary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Genre__c</fullName>
    <description>second most frequent genre of songs</description>
    <label>Secondary Genre</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs available for being included into Mixes. Has Name, Artist, Length and Genre</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of song</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Funk</fullName>
            </value>
            <value>
                <fullName>Hip hop</fullName>
            </value>
            <value>
                <fullName>K-pop</fullName>
            </value>
            <value>
                <fullName>Latin</fullName>
            </value>
            <value>
                <fullName>Polka</fullName>
            </value>
            <value>
                <fullName>Punk</fullName>
            </value>
            <value>
                <fullName>R&amp;B</fullName>
            </value>
            <value>
                <fullName>Reggae</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{00000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MixService.cls
public class MixService {
    public static void updateMixesGenres(Set<Id> mixesToUpdateIdSet) {
        List<Mix__c> mixesToUpdateList = [SELECT Id, 
                                                    Primary_Genre__c, 
                                                    Secondary_Genre__c, 
                                                    (SELECT Song__r.Genre__c FROM Tracks__r)
                                            FROM Mix__c
                                            WHERE Id IN :mixesToUpdateIdSet];

        for (Mix__c mix: mixesToUpdateList) {
            Map<String, Integer> genresAndAmount = getGenresAndAmount(mix);

            mix = getMixWithRecountedGenres(mix, genresAndAmount);
        }

        update mixesToUpdateList;
    }

    private static Mix__c getMixWithRecountedGenres(Mix__c mix, Map<String, Integer> genresAndAmount) {
        Integer primaryGenreCount = 0;
        String primaryGenre;

        Integer secondaryGenreCount = 0;
        String secondaryGenre;

        for (String key: genresAndAmount.keySet()) {
            if (primaryGenreCount < genresAndAmount.get(key)) {
                secondaryGenreCount = primaryGenreCount;
                secondaryGenre = primaryGenre;

                primaryGenreCount = genresAndAmount.get(key);
                primaryGenre = key;
            }
            else if (primaryGenreCount == genresAndAmount.get(key)) {
                secondaryGenreCount = genresAndAmount.get(key);
                secondaryGenre = key;
            }
            else if (secondaryGenreCount < genresAndAmount.get(key)) {
                secondaryGenreCount = genresAndAmount.get(key);
                secondaryGenre = key;
            }
        }

        mix.Primary_Genre__c = primaryGenre;
        mix.Secondary_Genre__c = secondaryGenre;

        return mix;
    }

    private static Map<String, Integer> getGenresAndAmount(Mix__c mix) {

        Map<String, Integer> genresWithAmount = new Map<String,Integer>();

        for(Track__c track: mix.Tracks__r) {
            String genre = track.Song__r.Genre__c;
            if (genresWithAmount.keySet().contains(genre)) {
                genresWithAmount.put(genre, genresWithAmount.get(genre) + 1);
            }
            else {
                genresWithAmount.put(genre, 1);
            }
        }

        return genresWithAmount;
    }
}   